//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.06 at 06:37:49 PM WEST 
//


package ma.ensa.cmi_service.requests_responses;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import ma.ensa.cmi_service.entities.realcardcmi.RealCardCMI;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="safeToken" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="card" type="{http://ensa.ma/cmi-service/entities/RealCardCMI}RealCardCMI"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "safeToken",
    "card"
})
@XmlRootElement(name = "AddRealCardRequest")
public class AddRealCardRequest {

    @XmlElement(required = true)
    protected String safeToken;
    @XmlElement(required = true)
    protected RealCardCMI card;

    /**
     * Gets the value of the safeToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafeToken() {
        return safeToken;
    }

    /**
     * Sets the value of the safeToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafeToken(String value) {
        this.safeToken = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link RealCardCMI }
     *     
     */
    public RealCardCMI getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealCardCMI }
     *     
     */
    public void setCard(RealCardCMI value) {
        this.card = value;
    }

}
