//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.06 at 06:37:49 PM WEST 
//


package ma.ensa.cmi_service.requests_responses;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ma.ensa.cmi_service.requests_responses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ma.ensa.cmi_service.requests_responses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddRealCardRequest }
     * 
     */
    public AddRealCardRequest createAddRealCardRequest() {
        return new AddRealCardRequest();
    }

    /**
     * Create an instance of {@link AddRealCardResponse }
     * 
     */
    public AddRealCardResponse createAddRealCardResponse() {
        return new AddRealCardResponse();
    }

    /**
     * Create an instance of {@link GetCardRequest }
     * 
     */
    public GetCardRequest createGetCardRequest() {
        return new GetCardRequest();
    }

    /**
     * Create an instance of {@link GetAllCardsRequest }
     * 
     */
    public GetAllCardsRequest createGetAllCardsRequest() {
        return new GetAllCardsRequest();
    }

    /**
     * Create an instance of {@link GetCardResponse }
     * 
     */
    public GetCardResponse createGetCardResponse() {
        return new GetCardResponse();
    }

    /**
     * Create an instance of {@link GetAllCardsResponse }
     * 
     */
    public GetAllCardsResponse createGetAllCardsResponse() {
        return new GetAllCardsResponse();
    }

}
