//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.06 at 07:12:59 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ensa.ma/cmi-service/requests_responses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ma.ensa.cmi_service.requests_responses;
