//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.06 at 03:19:18 PM WEST 
//


package ma.ensa.cmi_service.entities.realclientcmi;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlType;
import ma.ensa.cmi_service.entities.realcardcmi.RealCardCMI;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="saveToken" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="realCardsCMI" type="{http://ensa.ma/cmi-service/entities/RealCardCMI}RealCardCMI" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saveToken",
    "realCardsCMI"
})
@XmlRootElement(name = "RealClientCMI")
@Entity
public class RealClientCMI {

    @Id
    @XmlElement(required = true)
    protected String saveToken;
    @XmlElement(required = true)
    @XmlTransient
    @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.EAGER)
    protected List<RealCardCMI> realCardsCMI;

    /**
     * Gets the value of the saveToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaveToken() {
        return saveToken;
    }

    /**
     * Sets the value of the saveToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaveToken(String value) {
        this.saveToken = value;
    }

    /**
     * Gets the value of the realCardsCMI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the realCardsCMI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealCardsCMI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RealCardCMI }
     * 
     * 
     */
    public List<RealCardCMI> getRealCardsCMI() {
        if (realCardsCMI == null) {
            realCardsCMI = new ArrayList<RealCardCMI>();
        }
        return this.realCardsCMI;
    }

    public void setRealCardsCMI(ArrayList<RealCardCMI> realCardsCMI) {
        this.realCardsCMI = realCardsCMI;
    }

}
